baseURL = "itsnbal.xyz"
languageCode = "en-us"
title = "itsnbal"

[permalinks]
    blog = "/:filename/"

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home" 
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3


[params]
  dateFormat = "Jan 2, 2006"
    homeText = "You just made a Hugo blog from scratch."

